version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app1
    environment:
      CLIENT_ID: client1
      CLIENT_SECRET: client1secret
      REDIRECT_URI: http://app1:3000/callback
      AUTH_SERVER: http://auth-server:5000
      PORT: 3000
    ports:
      - "3000:3000"  # Map container port 3000 to host port 3000
    networks:
      - app-network
    depends_on:
      - auth-server

  auth-server:
    # Assuming you have a Dockerfile for your auth-server
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: auth-server
    environment:
      # Add necessary environment variables for auth-server
      PORT: 5000
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge