global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['server:5000']

  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092'] 